### ISSUE TITLE
Make Relative path available in ztk file (import item)

### ISSUE THREAD

**Issue by categoryik** [mi-lib/roki#8]
# Problem
.stl and others format is available as a shape in ztk file. Then we want to manage the model in a directory like ...
  - modelname/
    - /modelname.ztk
    - /shape1.stl
    - /shape2.stl
    - ...etc

but now, we need to describe full path for these component. it may reduce the portability of ztk model.

# Proposal
 - Make Relative path available in ztk file (import item)

**Comment by zhidao** [comment]
Actually, the ZTK evaluator imports files based on relative path names. In the above case, if you write:
```
import shape1.stl
```
in the modelname.ztk and open it at modelname/, it works as you expect.
So, I suppose you want to open the file at the parent directory of modelname/ (or anywhere other than modelname/), which doesn't work now.

This problem is not easy to resolve. In order to do so, we need to get the directory where the specified ZTK file is. Such a function is not defined in ANSI-C, namely, it is platform-dependent (see getcwd(), for example). It is against our design policy of the libraries.

Do you have some nice idea?

**Comment by categoryik** [comment]
Yes, I know we can write like `import: shape1.stl`.
Then, `rk_pen` is work as expected at only modelname directory.

```
Do you have some nice idea?
```
How about create a new method like `rkChain *rkChainReadZTK(rkChain *chain, char dirname[],  char filename[])`?
It may be just a workaround.

**Comment by zhidao** [comment]
I remember that rk_anim and rk_pen already have the function you want! See rk_penChainReadZTK() in rk_pen, for example. The following command totally works:

```% rk_pen modelname/modelname.ztk```

I think it is the best compromise to implement such application-level solutions.

**Comment by categoryik** [comment]
Thank you. I have confirmed `rk_pen` does work.

I have read around below link and understood how to implement.
https://github.com/mi-lib/roki-gl/blob/340ddc2a954a0b25fe72560bbbca4daa6fe942c5/app/rk_pen.c#L417
